channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal >=7.3
  - graphviz
  - samtools =1.15
  - perl
  - r-essentials
  - r-base =4.2.2
  - bioconductor-shortread
  - r-stringr
  - r-dplyr
  - r-vegan
