Bam: "/public/data1/yefq/data/fast5/20220703_WGA_twist/processed/20230426_Guppy621_comparison/Sce20_guppy_sup_aligned.softclip_trimmed.endtrim10_minimap2_align.mapped.sorted.bam"
Ref: "Zymo_Saccharomyces_cerevisiae_Seq5_ref"
Num: "5"
Tombo_dir: "/public/data1/yefq/data/fast5/20220703_WGA_twist/processed/20230426_guppy_sup_basecalled/Sce20/workspace/fast5_pass_single/all_single_fast5s"
Subsample: "2000"
Vcf: "/public/data1/yefq/data/fast5/20220703_WGA_twist/processed/20230426_Guppy621_comparison/Sce20_guppy_sup_aligned.test.vcf" #20240226 updated
Refseq: "/public/data1/yefq/data/Refs/Zymo_Saccharomyces_cerevisiae_Seq5_ref.fa" #240225 updated
Outdir: "/public/data1/yefq/data/fast5/20220703_WGA_twist/processed/20230426_Guppy621_comparison/snakemake-tutorial/data/test" #240225 updated



# #假设在config.yaml文件中用out_dir指明输出目录。之后在snakefile中用config["out_dir"]调用
# out_dir: /home/zhaohuiyao/Genome_survey/Snakemake/
# # #也可以在config.yaml文件中不指明。在执行snakefile时
# # snakefile -s snakefile.py -p -c 8 --use-conda --config out_dir=/home/zhaohuiyao/Genome_survey/Snakemake/

# workdir: ./testresults/   

# #config.yaml文件。下面是三种经典变量
# kmername: "21kmer_shuxi"
# fastp_dir: /home/zhaohuiyao/Biosoft/
# samples:
#         test_L1:
#                 ["../testdata/test_L1_1.fq","../testdata/test_L1_2.fq"]
#         test_L2:
#                 ["../testdata/test_L2_1.fq","../testdata/test_L2_2.fq"]
# adaptor_seq: ["GATCGGAAGAGCACACGTCTGAACTCCAGTCACACGAGAATGCATCTCGTATGCCGTCTTCTGCTTG","AGATCGGAAGAGCGTCGTGTAGGGAAAGA"]

# #因为config.yaml文件被读入时，是字典。字典就有key值和对应的value值。上面的文件中，key值分别是kmername、fastp_dir、samples、adaptor_seq。那么对应的value值表示就是config["kmername"]这样
# # #snakemake文件

# # NAME=config["kmername"]       #NAME变量是一个字符串，内容是21kmer_shuxi
# # FASTP_DIR=config["fastp_dir"]   #FASTP_DIR变量是一个字符串，内容是/home/zhaohuiyao/Biosoft/。因此这个引号""，在只有一个变量是可有可无
# # SAMPLES=config["samples"]     #SAMPLES变量是一个字典，有两个key值，分别是test_L1和test_L2，有各自的value值
# # SAMPLES=config["samples"].keys()  #SAMPLES变量是一个字典的keys信息列表。仅包括test_L1和test_L2
# # ADAPTORS=config["adaptor_seq"]    #ADAPTORS变量是一个列表，长度为2。在之后的shell中调用，{ADAPTORS[0]}和{ADAPTORS[1]}。若在python语句中则只需要ADAPTORS[0]即可。

